---
- name: Slurp node-token for cluster-join from bootstrap node
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  delegate_to: "{{ k3s_config_init_server }}"
  run_once: true
  register: _cluster_node_token
  when: not k3s_config_cluster_init

- name: Validate k3s config folder
  ansible.builtin.stat:
    path: /etc/rancher/ks
  register: _k3s_config_folder

- name: Create k3s config folder
  ansible.builtin.file:
    state: directory
    path: /etc/rancher/k3s
    mode: "0755"
    owner: root
    group: root
    recurse: true
  when: not _k3s_config_folder.stat.exists

- name: Configure k3s
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: "0755"
    owner: root
    group: root
  notify:
    - Systemctl daemon-reload
    - Restart k3s

- name: Create k3s service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    mode: "0644"
    owner: root
    group: root
  notify:
    - Systemctl daemon-reload
    - Restart k3s

- name: Validate k3s manifests folder
  ansible.builtin.stat:
    path: /var/lib/rancher/k3s/server/manifests
  register: _k3s_maniftests_folder

- name: Ensure manifests folder exists
  ansible.builtin.file:
    state: directory
    path: /var/lib/rancher/k3s/server/manifests
    recurse: true
    owner: root
    group: root
    mode: "0644"
  when: not _k3s_maniftests_folder.stat.exists

- name: Configure ingress traefik tls
  when: k3s_traefik_tls
  block:
    - name: Assert traefilk tls settings are provided
      ansible.builtin.assert:
        that:
          - k3s_traefik_tls_key | length > 0
          - k3s_traefik_tls_crt | length > 0

    - name: Place ingress-traefik-tls manifest for TLS
      ansible.builtin.template:
        src: manifests/ingress-traefik-tls.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/ingress-traefik-tls.yaml
        owner: root
        group: root
        mode: "0644"

- name: Configure kube-vip
  when: k3s_kube_vip
  block:
    - name: Assert kube-vip settings are provided
      ansible.builtin.assert:
        that:
          - k3s_kube_vip_ipv4 | length > 0
          - k3s_kube_vip_interface | length > 0

    - name: Place kube-vip manifest for cluster-ip
      ansible.builtin.template:
        src: manifests/kube-vip.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
        owner: root
        group: root
        mode: "0644"

- name: Configure nfs-csi storage driver
  when:
    - k3s_storage_nfs
  block:
    - name: Assert nfs-csi settings are provided
      ansible.builtin.assert:
        that:
          - k3s_storage_nfs_server | length > 0
          - k3s_storage_nfs_server_share | length > 0

    - name: Place manifest for csi-nfs-driver
      ansible.builtin.template:
        src: manifests/csi-nfs-driver.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/csi-nfs-driver.yaml
        owner: root
        group: root
        mode: "0644"

- name: Configure argocd
  when: k3s_argocd
  block:
    - name: Assert argocd settings are provided
      ansible.builtin.assert:
        that:
          - k3s_argocd_ingress_hostname | length > 0

    - name: Place argocd manifest
      ansible.builtin.template:
        src: manifests/argocd.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/argocd.yaml
        owner: root
        group: root
        mode: "0644"
