---
- name: Install os specific packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ k3s_os_packages }}"
  when: k3s_os_packages | length > 0

- name: Fetch k3s from source
  ansible.builtin.get_url:
    url: "{{ k3s_binary_source }}"
    dest: "{{ k3s_binary_path }}"
    mode: '0755'
    owner: root
    group: root

- name: Fetch kubectl from source
  ansible.builtin.get_url:
    url: "{{ k3s_binary_source_kubectl }}"
    dest: "{{ k3s_binary_path_kubectl }}"
    mode: '0755'
    owner: root
    group: root

- name: Enable kubectl auto-completion
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    regex: '^source <\(kubectl completion bash\)'
    line: source <(kubectl completion bash)
  when: k3s_enable_kubectl_auto_completion
