---
# k3s installed? k3s running? k3s server type?
# install k3s
# configure k3s
# changes made that are only possible when new init?
# start k3s
# cluster status?

- name: Include pre-audit node/cluster status
  ansible.builtin.include_tasks: pre-audit.yml
