---
- name: Populate service_facts
  ansible.builtin.service_facts:

- name: Check if k3s is installed
  ansible.builtin.set_fact:
    _k3s_installed: "{{ ('k3s' in ansible_facts.services) | default(false) }}"

- name: Check if k3s is running
  ansible.builtin.set_fact:
    _k3s_running: "{{ ansible.facts.services[k3s].status == 'running' }}"
  when: _k3s_installed
