---
- name: Get stat for k3s binary
  ansible.builtin.stat:
    path: "{{ k3s_binary_path }}"
  register: _k3s_binary_stat

- name: Register k3s installation status
  ansible.builtin.set_fact:
    _k3s_installed: "{{ _k3s_binary_stat.stat.exists }}"
