[all:children]
k3s-cluster-init
k3s-cluster-joiner
k3s-nfs

[k3s-cluster-init]
k3s-test01  ansible_host=k3s-test01 ansible_user=vagrant

[k3s-cluster-joiner]
k3s-test02  ansible_host=k3s-test02 ansible_user=vagrant

[k3s-nfs]
k3s-nfs     ansible_host=k3s-nfs ansible_user=vagrant
