---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: k3s-node01
    image: "docker.io/geerlingguy/docker-debian13-ansible:latest"
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: k3s-node02
    image: "docker.io/geerlingguy/docker-debian13-ansible:latest"
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../
  name: ansible
